["Status changed:Start training","Status changed:Pending:null:null","Status changed:Running:null:null","Model management server:https://kubernetes-internal-b60a62f4e1d24d21.elb.us-west-2.amazonaws.com/model-management","Model:keras-creditcard","Version:2","Training ID:trainer-keras-keras-creditcard-2-cpu-62c31297","Downloading files for training","Python 3.5.2","  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current","                                 Dload  Upload   Total   Spent    Left  Speed","  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0","100  1732    0  1732    0     0   6833      0 --:--:-- --:--:-- --:--:--  6845","  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current","                                 Dload  Upload   Total   Spent    Left  Speed","  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0","100   243  100   243    0     0   1490      0 --:--:-- --:--:-- --:--:--  1500","  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current","                                 Dload  Upload   Total   Spent    Left  Speed","  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0","100   232  100   232    0     0   1924      0 --:--:-- --:--:-- --:--:--  1933","No pipeline supplied","Extract information","Start training","Using TensorFlow backend.","Downloading csv resource from https://s3-us-west-2.amazonaws.com/ukkhdeh3ptsk8kh3/creditcard_validation.csv for [training]","Downloading csv resource from https://s3-us-west-2.amazonaws.com/ukkhdeh3ptsk8kh3/creditcard.csv for [validation]","Epoch 1/1","Traceback (most recent call last):","  File \"driver.py\", line 92, in <module>","    keras_model.fit_generator(training_iterator, steps_per_epoch=epoch_steps, epochs=int(nr_epoch))","  File \"/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py\", line 87, in wrapper","    return func(*args, **kwargs)","  File \"/usr/local/lib/python3.5/dist-packages/keras/models.py\", line 1227, in fit_generator","    initial_epoch=initial_epoch)","  File \"/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py\", line 87, in wrapper","    return func(*args, **kwargs)","  File \"/usr/local/lib/python3.5/dist-packages/keras/engine/training.py\", line 2147, in fit_generator","    class_weight=class_weight)","  File \"/usr/local/lib/python3.5/dist-packages/keras/engine/training.py\", line 1833, in train_on_batch","    check_batch_axis=True)","  File \"/usr/local/lib/python3.5/dist-packages/keras/engine/training.py\", line 1414, in _standardize_user_data","    exception_prefix='input')","  File \"/usr/local/lib/python3.5/dist-packages/keras/engine/training.py\", line 141, in _standardize_input_data","    str(array.shape))","ValueError: Error when checking input: expected lstm_1_input to have 3 dimensions, but got array with shape (2, 30)","Can not find performance json file:[performance.json]","Unable to read output folder:[output]","Execution finished"]